### ISSUE TITLE
Error encountered during training on GO datasets. 

### ISSUE THREAD

**Issue by gokceuludogan** [a-r-j/ProteinWorkshop#69]
Hi, 

I would like first to thank you for this impressive work.

I'm experiencing a problem with training a Graph Convolutional Network (GCN) using the GO datasets in the **`proteinworkshop`** framework.

Initially, I encountered a **`RuntimeError`** related to the PytorchStreamReader during data loading. I believe this was due to environmental incompatibility. To address this, I set **`in_memory=False`** in the dataset configurations (**`go-mf.yaml`** and **`go-cc.yaml`**).

However, when I ran the training commands:

```bash
python proteinworkshop/train.py dataset=go-mf encoder=gcn task=multiclass_graph_classification trainer=gpu
python proteinworkshop/train.py dataset=go-cc encoder=gcn task=multiclass_graph_classification trainer=gpu
```

I faced a new issue: the input and target batch sizes did not match in both instances.

I've included the full error trace below for your reference. I would greatly appreciate any advice or suggestions to resolve this issue.

**Comment by gokceuludogan** [comment]
```bash
Error executing job with overrides: ['dataset=go-mf', 'encoder=gcn', 'task=multiclass_graph_classification', 'trainer=gpu', 'trainer.max_epochs=100']
Traceback (most recent call last):
  File "/users/gokce.uludogan/bioinformatics/ProteinWorkshop/proteinworkshop/train.py", line 235, in <module>
    _main()  # type: ignore
  File "/opt/python3/venv/base/lib/python3.10/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/opt/python3/venv/base/lib/python3.10/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/opt/python3/venv/base/lib/python3.10/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/opt/python3/venv/base/lib/python3.10/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/opt/python3/venv/base/lib/python3.10/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/opt/python3/venv/base/lib/python3.10/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/opt/python3/venv/base/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/opt/python3/venv/base/lib/python3.10/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/opt/python3/venv/base/lib/python3.10/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/users/gokce.uludogan/bioinformatics/ProteinWorkshop/proteinworkshop/train.py", line 218, in _main
    train_model(cfg)
  File "/users/gokce.uludogan/bioinformatics/ProteinWorkshop/proteinworkshop/train.py", line 182, in train_model
    trainer.fit(
  File "/opt/python3/venv/base/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "/opt/python3/venv/base/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/opt/python3/venv/base/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/opt/python3/venv/base/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 989, in _run
    results = self._run_stage()
  File "/opt/python3/venv/base/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 1033, in _run_stage
    self._run_sanity_check()
  File "/opt/python3/venv/base/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 1062, in _run_sanity_check
    val_loop.run()
  File "/opt/python3/venv/base/lib/python3.10/site-packages/lightning/pytorch/loops/utilities.py", line 182, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/opt/python3/venv/base/lib/python3.10/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 134, in run
    self._evaluation_step(batch, batch_idx, dataloader_idx, dataloader_iter)
  File "/opt/python3/venv/base/lib/python3.10/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 391, in _evaluation_step
    output = call._call_strategy_hook(trainer, hook_name, *step_args)
  File "/opt/python3/venv/base/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 309, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/opt/python3/venv/base/lib/python3.10/site-packages/lightning/pytorch/strategies/strategy.py", line 403, in validation_step
    return self.lightning_module.validation_step(*args, **kwargs)
  File "/users/gokce.uludogan/bioinformatics/ProteinWorkshop/proteinworkshop/models/base.py", line 643, in validation_step
    return self._do_step(batch, batch_idx, "val")
  File "<@beartype(proteinworkshop.models.base.BenchMarkModel._do_step) at 0x7fb7dd731870>", line 80, in _do_step
  File "/users/gokce.uludogan/bioinformatics/ProteinWorkshop/proteinworkshop/models/base.py", line 597, in _do_step
    loss = self.compute_loss(y_hat, y)
  File "<@beartype(proteinworkshop.models.base.BaseModel.compute_loss) at 0x7fb7dd730ca0>", line 48, in compute_loss
  File "/users/gokce.uludogan/bioinformatics/ProteinWorkshop/proteinworkshop/models/base.py", line 197, in compute_loss
    loss = {k: v(y_hat[k], y[k]) for k, v in self.losses.items()}
  File "/users/gokce.uludogan/bioinformatics/ProteinWorkshop/proteinworkshop/models/base.py", line 197, in <dictcomp>
    loss = {k: v(y_hat[k], y[k]) for k, v in self.losses.items()}
  File "/opt/python3/venv/base/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/python3/venv/base/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/python3/venv/base/lib/python3.10/site-packages/torch/nn/modules/loss.py", line 1179, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "/opt/python3/venv/base/lib/python3.10/site-packages/torch/nn/functional.py", line 3053, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
ValueError: Expected input batch_size (32) to match target batch_size (175).
```

**Comment by gokceuludogan** [comment]
```bash
Error executing job with overrides: ['dataset=go-cc', 'encoder=gcn', 'task=multiclass_graph_classification', 'trainer=gpu', 'trainer.max_epochs=100']
Traceback (most recent call last):
  File "/users/gokce.uludogan/bioinformatics/ProteinWorkshop/proteinworkshop/train.py", line 235, in <module>
    _main()  # type: ignore
  File "/opt/python3/venv/base/lib/python3.10/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/opt/python3/venv/base/lib/python3.10/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/opt/python3/venv/base/lib/python3.10/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/opt/python3/venv/base/lib/python3.10/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/opt/python3/venv/base/lib/python3.10/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/opt/python3/venv/base/lib/python3.10/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/opt/python3/venv/base/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/opt/python3/venv/base/lib/python3.10/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/opt/python3/venv/base/lib/python3.10/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/users/gokce.uludogan/bioinformatics/ProteinWorkshop/proteinworkshop/train.py", line 218, in _main
    train_model(cfg)
  File "/users/gokce.uludogan/bioinformatics/ProteinWorkshop/proteinworkshop/train.py", line 182, in train_model
    trainer.fit(
  File "/opt/python3/venv/base/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "/opt/python3/venv/base/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/opt/python3/venv/base/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/opt/python3/venv/base/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 989, in _run
    results = self._run_stage()
  File "/opt/python3/venv/base/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 1033, in _run_stage
    self._run_sanity_check()
  File "/opt/python3/venv/base/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 1062, in _run_sanity_check
    val_loop.run()
  File "/opt/python3/venv/base/lib/python3.10/site-packages/lightning/pytorch/loops/utilities.py", line 182, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/opt/python3/venv/base/lib/python3.10/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 134, in run
    self._evaluation_step(batch, batch_idx, dataloader_idx, dataloader_iter)
  File "/opt/python3/venv/base/lib/python3.10/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 391, in _evaluation_step
    output = call._call_strategy_hook(trainer, hook_name, *step_args)
  File "/opt/python3/venv/base/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 309, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/opt/python3/venv/base/lib/python3.10/site-packages/lightning/pytorch/strategies/strategy.py", line 403, in validation_step
    return self.lightning_module.validation_step(*args, **kwargs)
  File "/users/gokce.uludogan/bioinformatics/ProteinWorkshop/proteinworkshop/models/base.py", line 643, in validation_step
    return self._do_step(batch, batch_idx, "val")
  File "<@beartype(proteinworkshop.models.base.BenchMarkModel._do_step) at 0x7feffbf896c0>", line 80, in _do_step
  File "/users/gokce.uludogan/bioinformatics/ProteinWorkshop/proteinworkshop/models/base.py", line 597, in _do_step
    loss = self.compute_loss(y_hat, y)
  File "<@beartype(proteinworkshop.models.base.BaseModel.compute_loss) at 0x7feffbf88af0>", line 48, in compute_loss
  File "/users/gokce.uludogan/bioinformatics/ProteinWorkshop/proteinworkshop/models/base.py", line 197, in compute_loss
    loss = {k: v(y_hat[k], y[k]) for k, v in self.losses.items()}
  File "/users/gokce.uludogan/bioinformatics/ProteinWorkshop/proteinworkshop/models/base.py", line 197, in <dictcomp>
    loss = {k: v(y_hat[k], y[k]) for k, v in self.losses.items()}
  File "/opt/python3/venv/base/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/python3/venv/base/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/python3/venv/base/lib/python3.10/site-packages/torch/nn/modules/loss.py", line 1179, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "/opt/python3/venv/base/lib/python3.10/site-packages/torch/nn/functional.py", line 3053, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
ValueError: Expected input batch_size (32) to match target batch_size (168).
```

**Comment by a-r-j** [comment]
Hi @gokceuludogan thanks for raising this. This is expected behaviour actually. Can you try with `task=multilabel_graph_classification`. Apologies if this is not clear - is there anywhere we need to update the documentation?
